from setuptools import setup, find_packages

setup(
    name='DL_HAWKES_PROCESS_ESTIMATION',
    version='1.0',
    description='DL & HAWKES PROCESS ESTIMATION',
    author='Nicolas Girard',
    author_email='nico.girard22@gmail.com',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    packages=find_packages(),
    install_requires=['numpy', 'pandas', 
                      'hawkes', 'torch>=1.9.0', 
                      'tensorflow>=2.0', 'tqdm', 
                      'torchinfo'],
    extras_require={'mpi': ['mpi4py'], 'test': ['pytest', 'pytest-cov', 'codecov']},
    classifiers=['Development Status :: 3 - Alpha',
                 'Environment :: Console',
                 'Environment :: Win32 (MS Windows)',
                 'Intended Audience :: Developers',
                 'Intended Audience :: Science/Research',
                 'Intended Audience :: Information Technology',
                 'Intended Audience :: Financial and Insurance Industry',
                 'License :: OSI Approved :: MIT License',
                 'Natural Language :: English',
                 'Operating System :: Microsoft :: Windows',
                 'Programming Language :: Python :: 3.11',
                 'Topic :: Office/Business :: Financial :: Investment',
                 'Topic :: Scientific/Engineering :: Artificial Intelligence'
                ],
)
